osx_image: xcode8

sudo: false

language: cpp

matrix:
  include:
    - os: osx
      compiler: gcc
      env:
        - XMRIGCC_CMAKE_FLAGS="-DUV_LIBRARY=/usr/local/lib/libuv.a -DOPENSSL_SSL_LIBRARY=/usr/local/opt/openssl/lib/libssl.a -DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl/lib/libcrypto.a -DBOOST_ROOT=/usr/local/lib -DWITH_CC_SERVER=OFF -DWITH_HTTPD=OFF"

before_install:
      brew update

script:
  - brew install gcc libuv libmicrohttpd
  - brev upgrade boost
  - cmake ${XMRIGCC_CMAKE_FLAGS} .
  - make
  - ./xmrigDaemon --version
