# image
image: Visual Studio 2017

# build platform
platform: x64

# clone directory
clone_folder: c:\xmrigCC

install:
  - vcpkg install libuv:x64-windows
  - vcpkg install libmicrohttpd:x64-windows

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
  - cd c:\xmrigCC
  - mkdir build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 ..
  - msbuild xmrig.sln /p:Configuration=Release
