# image
image: Visual Studio 2017

# build platform
platform: x64

# clone directory
clone_folder: c:\xmrigCC

install:
  - mkdir c:\xmrigCC-deps
  - curl -sL https://github.com/xmrig/xmrig-deps/releases/download/v2/xmrig-deps-v2.zip -o xmrigCC-deps-v2.zip
  - 7z x xmrigCC-deps-v2.zip -o"c:\xmrigCC-deps" -y > nul

build_script:


after_build:
- cmd: 7z a c:\xmrigCC\xmrigCC.zip "c:\xmrigCC\*.*"
artifacts:
- path: c:\xmrigCC\xmrigCC.zip
